export const countries = [
    {
      entity: "Afghanistan",
      capital: "Kabul",
      num: 13,
      cc: "AF",
      alpha3: "AFG",
      ccTLD: ".AF",
      iac: "+93",
      idd: "00",
      timezone: "UTC+04:30",
      currency: "Afghan afghani (AFN, ؋)",
      "Language(s)":
        "Pashto, Dari, and some other languages in areas where spoken by majority of population",
    },
    {
      entity: "Albania",
      capital: "Tirana",
      num: 12,
      cc: "AL",
      alpha3: "ALB",
      ccTLD: ".AL",
      iac: "+355",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Albanian lek (ALL, L)",
      "Language(s)": "Albanian (based on Tosk dialect)",
    },
    {
      entity: "Algeria",
      capital: "Algiers",
      num: 11,
      cc: "DZ",
      alpha3: "DZA",
      ccTLD: ".DZ",
      iac: "+213",
      idd: "00",
      timezone: "UTC",
      currency: "Algerian dinar (DZD, د.ج)",
      "Language(s)": "Arabic (official and national), Tamazight (national)",
    },
  
    {
      entity: "Andorra",
      capital: "Andorra la Vella",
      num: 12,
      cc: "AD",
      alpha3: "AND",
      ccTLD: ".AD",
      iac: "+376",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Catalan",
    },
    {
      entity: "Antigua and Barbuda",
      capital: "St. John's",
      num: 12,
      cc: "AG",
      alpha3: "ATG",
      ccTLD: ".AG",
      iac: "+1 268",
      idd: "011",
      timezone: "UTC-04:00",
      currency: "East Caribbean dollar (XCD, $)",
      "Language(s)": "English (de facto official)",
    },
    {
      entity: "Argentina",
      capital: "Buenos Aires",
      num: 10,
      cc: "AR",
      alpha3: "ARG",
      ccTLD: ".AR",
      iac: "+54",
      idd: "00",
      timezone: "UTC-03:00",
      currency: "Argentine peso (ARS, $)",
      "Language(s)":
        "Spanish (de facto), Guaraní (co-official in Corrientes Province)",
    },
    {
      entity: "Armenia",
      capital: "Yerevan",
      num: 8,
      cc: "AM",
      alpha3: "ARM",
      ccTLD: ".AM",
      iac: "+374",
      idd: "00",
      timezone: "UTC+04:00",
      currency: "Armenian dram (AMD, դր.)",
      "Language(s)": "Armenian, Russian (Minority language)",
    },
    {
      entity: "Aruba",
      capital: "Oranjestad",
      num: 12,
      cc: "AW",
      alpha3: "ABW",
      ccTLD: ".AW",
      iac: "+297",
      idd: "00",
      timezone: "UTC-04:00",
      currency: "Aruban florin (AWG, ƒ)",
      "Language(s)": "Dutch, Papiamento",
    },
    {
      entity: "Australia",
      capital: "Canberra",
      num: 10,
      cc: "AU",
      alpha3: "AUS",
      ccTLD: ".AU",
      iac: "+61",
      idd: "0011",
      timezone: "UTC+07:00 - UTC+10:00",
      currency: "Australian dollar (AUD, $)",
      "Language(s)": "English (de facto)",
    },
    {
      entity: "Austria",
      capital: "Vienna",
      num: 13,
      cc: "AT",
      alpha3: "AUT",
      ccTLD: ".AT",
      iac: "+43",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)":
        "German (official statewide), and other languages like Groation, Slovene, Czech for some areas.",
    },
    {
      entity: "Azerbaijan",
      capital: "Baku",
      num: 10,
      cc: "AZ",
      alpha3: "AZE",
      ccTLD: ".AZ",
      iac: "+994",
      idd: "00",
      timezone: "UTC+04:00",
      currency: "Azerbaijani manat (AZN, )",
      "Language(s)": "Azerbaijani, Armenian (Nagorno-Karabagh)",
    },
    {
      entity: "Bahamas",
      capital: "Nassau",
      num: 11,
      cc: "BS",
      alpha3: "BHS",
      ccTLD: ".BS",
      iac: "+1 242",
      idd: "011",
      timezone: "UTC-05:00",
      currency: "Bahamian dollar (BSD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Bahrain",
      capital: "Manama",
      num: 12,
      cc: "BH",
      alpha3: "BHR",
      ccTLD: ".BH",
      iac: "+973",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Bahraini dinar (BHD, .د.ب)",
      "Language(s)": "Arabic",
    },
    {
      entity: "Bangladesh",
      capital: "Dhaka",
      num: 12,
      cc: "BD",
      alpha3: "BGD",
      ccTLD: ".BD",
      iac: "+880",
      idd: "00",
      timezone: "UTC+06:00",
      currency: "Bangladeshi taka (BDT, ৳)",
      "Language(s)": "Bengali",
    },
    {
      entity: "Barbados",
      capital: "Bridgetown",
      num: 52,
      cc: "BB",
      alpha3: "BRB",
      ccTLD: ".BB",
      iac: "+1 246",
      idd: "011",
      timezone: "UTC-04:00",
      currency: "Barbadian dollar (BBD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Belarus",
      capital: "Minsk",
      num: 12,
      cc: "BY",
      alpha3: "BLR",
      ccTLD: ".BY",
      iac: "+375",
      idd: "8~10",
      timezone: "UTC+03:00",
      currency: "Belarusian ruble (BYR, Br)",
      "Language(s)": "Belarusian, Russian",
    },
    {
      entity: "Belgium",
      capital: "Brussels",
      num: 9,
      cc: "BE",
      alpha3: "BEL",
      ccTLD: ".BE",
      iac: "+32",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Dutch, French, German",
    },
    {
      entity: "Belize",
      capital: "Belmopan",
      num: 12,
      cc: "BZ",
      alpha3: "BLZ",
      ccTLD: ".BZ",
      iac: "+501",
      idd: "00",
      timezone: "UTC-06:00",
      currency: "Belize dollar (BZD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Benin",
      capital: "Porto-Novo",
      num: 12,
      cc: "BJ",
      alpha3: "BEN",
      ccTLD: ".BJ",
      iac: "+229",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "West African CFA franc (XOF, Fr)",
      "Language(s)": "French",
    },
    {
      entity: "Bhutan",
      capital: "Thimphu",
      num: 12,
      cc: "BT",
      alpha3: "BTN",
      ccTLD: ".BT",
      iac: "+975",
      idd: "00",
      timezone: "UTC+05:30",
      currency: "Bhutanese ngultrum (BTN, Nu.), Indian rupee (INR, ₹)",
      "Language(s)": "Dzongkha",
    },
    {
      entity: "Bolivia",
      capital: "Sucre",
      num: 12,
      cc: "BO",
      alpha3: "BOL",
      ccTLD: ".BO",
      iac: "+591",
      idd: "00",
      timezone: "UTC-04:00",
      currency: "Bolivian boliviano (BOB, Bs.)",
      "Language(s)": "Spanish, Aymara, Quechua",
    },
    {
      entity: "Bosnia and Herzegovina",
      capital: "Sarajevo",
      num: 12,
      cc: "BA",
      alpha3: "BIH",
      ccTLD: ".BA",
      iac: "+387",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Bosnia and Herzegovina convertible mark (BAM, KM or КМ)",
      "Language(s)": "Bosnian, Croatian, Serbian",
    },
    {
      entity: "Botswana",
      capital: "Gaborone",
      num: 12,
      cc: "BW",
      alpha3: "BWA",
      ccTLD: ".BW",
      iac: "+267",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Botswana pula (BWP, P)",
      "Language(s)": "English, Tswana (national)",
    },
    {
      entity: "Brazil",
      capital: "Brasília",
      num: 11,
      cc: "BR",
      alpha3: "BRA",
      ccTLD: ".BR",
      iac: "+55",
      idd: "00",
      timezone: "UTC-05:00 - UTC-03:00",
      currency: "Brazilian real (BRL, R$)",
      "Language(s)":
        "Portuguese (national), German, Nheengatu, Baniwa and Tucano in some areas.",
    },
    {
      entity: "British Indian Ocean Territory",
      capital: "Diego Garcia",
      num: 12,
      cc: "IO",
      alpha3: "IOT",
      ccTLD: ".IO",
      iac: "+246",
      idd: "00",
      timezone: "UTC+06",
      currency: "United States dollar (USD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Brunei",
      capital: "Bandar Seri Begawan",
      num: 12,
      cc: "BN",
      alpha3: "BRN",
      ccTLD: ".BN",
      iac: "+673",
      idd: "00",
      timezone: "UTC+08:00",
      currency: "Brunei dollar (BND, $), Singapore dollar (SGD, $)",
      "Language(s)": "Malay",
    },
    {
      entity: "Bulgaria",
      capital: "Sofia",
      num: 12,
      cc: "BG",
      alpha3: "BGR",
      ccTLD: ".BG",
      iac: "+359",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Bulgarian lev (BGN, лв)",
      "Language(s)": "Bulgarian",
    },
    {
      entity: "Burkina Faso",
      capital: "Ouagadougou",
      num: 12,
      cc: "BF",
      alpha3: "BFA",
      ccTLD: ".BF",
      iac: "+226",
      idd: "00",
      timezone: "UTC",
      currency: "West African CFA franc (XOF, Fr)",
      "Language(s)": "French, Fula, Jula, More",
    },
    {
      entity: "Burundi",
      capital: "Bujumbura",
      num: 12,
      cc: "BI",
      alpha3: "BDI",
      ccTLD: ".BI",
      iac: "+257",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Burundian franc (BIF, Fr)",
      "Language(s)": "French, Kirundi",
    },
    {
      entity: "Cambodia",
      capital: "Phnom Penh",
      num: 12,
      cc: "KH",
      alpha3: "KHM",
      ccTLD: ".KH",
      iac: "+855",
      idd: "001",
      timezone: "UTC+07:00",
      currency: "Cambodian riel (KHR, ៛)",
      "Language(s)": "Khmer",
    },
    {
      entity: "Cameroon",
      capital: "Yaoundé",
      num: 12,
      cc: "CM",
      alpha3: "CMR",
      ccTLD: ".CM",
      iac: "+237",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Central African CFA franc (XAF, Fr)",
      "Language(s)": "English, French",
    },
    {
      entity: "Cape Verde",
      capital: "Praia",
      num: 12,
      cc: "CV",
      alpha3: "CPV",
      ccTLD: ".CV",
      iac: "+238",
      idd: "0",
      timezone: "UTC-01:00",
      currency: "Cape Verdean escudo (CVE, Esc or $)",
      "Language(s)": "Portuguese (official), Cape Verdean Creole (national)",
    },
    {
      entity: "Central African Republic",
      capital: "Bangui",
      num: 12,
      cc: "CF",
      alpha3: "CAF",
      ccTLD: ".CF",
      iac: "+236",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Central African CFA franc (XAF, Fr)",
      "Language(s)": "French, Sango (national)",
    },
    {
      entity: "Chad",
      capital: "N'Djamena",
      num: 12,
      cc: "TD",
      alpha3: "TCD",
      ccTLD: ".TD",
      iac: "+235",
      idd: "15",
      timezone: "UTC+01:00",
      currency: "Central African CFA franc (XAF, Fr)",
      "Language(s)": "Arabic, French",
    },
    {
      entity: "Chile",
      capital: "Santiago",
      num: 13,
      cc: "CL",
      alpha3: "CHL",
      ccTLD: ".CL",
      iac: "+56",
      idd: "00",
      timezone: "UTC-04:00",
      currency: "Chilean peso (CLP, $)",
      "Language(s)": "Spanish (de facto)",
    },
    {
      entity: "China",
      capital: "Beijing",
      num: 11,
      cc: "CN",
      alpha3: "CHN",
      ccTLD: ".CN",
      iac: "+86",
      idd: "00",
      timezone: "UTC+08:00",
      currency: "Chinese yuan (CNY, ¥ or ? ?)",
      "Language(s)":
        "Simplified Chinese(written) Mandarin(spoken), and some other minority languages in some areas.",
    },
    {
      entity: "Colombia",
      capital: "Bogotá",
      num: 10,
      cc: "CO",
      alpha3: "COL",
      ccTLD: ".CO",
      iac: "+57",
      idd: "00",
      timezone: "UTC-05:00",
      currency: "Colombian peso (COP, $)",
      "Language(s)":
        "Spanish (the languages and dialects of ethnic groups are also official in their territories)",
    },
    {
      entity: "Comoros",
      capital: "Moroni",
      num: 12,
      cc: "KM",
      alpha3: "COM",
      ccTLD: ".KM",
      iac: "",
      idd: "",
      timezone: "UTC+03:00",
      currency: "Comorian franc (KMF, Fr)",
      "Language(s)": "Arabic, Comorian, French",
    },
    {
      entity: "Congo, Republic of the",
      capital: "Brazzaville",
      num: 12,
      cc: "CG",
      alpha3: "COG",
      ccTLD: ".CG",
      iac: "+242",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Central African CFA franc (XAF, Fr)",
      "Language(s)": "French, Lingala (national), Munukutuba (national)",
    },
    {
      entity: "Congo, the Democratic Republic of the",
      capital: "Kinshasa",
      num: 12,
      cc: "CD",
      alpha3: "COD",
      ccTLD: ".CD",
      iac: "+243",
      idd: "00",
      timezone: "UTC+01:00 - UTC+02:00",
      currency: "Congolese franc (CDF, Fr)",
      "Language(s)": "French, Lingala/Kikongo/Swahili/Tshiluba (national)",
    },
    {
      entity: "Costa Rica",
      capital: "San José",
      num: 8,
      cc: "CR",
      alpha3: "CRI",
      ccTLD: ".CR",
      iac: "+506",
      idd: "00",
      timezone: "UTC-06:00",
      currency: "Costa Rican colón (CRC, ₡)",
      "Language(s)": "Spanish",
    },
    {
      entity: "Côte d'Ivoire",
      capital: "Yamoussoukro",
      num: 8,
      cc: "CI",
      alpha3: "CIV",
      ccTLD: ".CI",
      iac: "+225",
      idd: "00",
      timezone: "",
      currency: "West African CFA franc (XOF, Fr)",
      "Language(s)": "French",
    },
    {
      entity: "Croatia",
      capital: "Zagreb",
      num: 12,
      cc: "HR",
      alpha3: "HRV",
      ccTLD: ".HR",
      iac: "+385",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Croatian kuna (HRK, kn)",
      "Language(s)": "Croatian",
    },
    {
      entity: "Cuba",
      capital: "Havana",
      num: 13,
      cc: "CU",
      alpha3: "CUB",
      ccTLD: ".CU",
      iac: "+53",
      idd: "119",
      timezone: "UTC-03:00",
      currency: "Cuban convertible peso (CUC, $), Cuban peso (CUP, $)",
      "Language(s)": "Spanish",
    },
    {
      entity: "Curaçao",
      capital: "Willemstad",
      num: 13,
      cc: "CW",
      alpha3: "CUW",
      ccTLD: ".CW",
      iac: "+599 9",
      idd: "00",
      timezone: "",
      currency: "Netherlands Antillean guilder (ANG, ƒ)",
      "Language(s)": "Papiamentu, Dutch(official)",
    },
    {
      entity: "Cyprus",
      capital: "Nicosia",
      num: 8,
      cc: "CY",
      alpha3: "CYP",
      ccTLD: ".CY",
      iac: "+357",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Greek, Turkish, Armenian (minority language)",
    },
    {
      entity: "Czech Republic",
      capital: "Prague",
      num: 9,
      cc: "CZ",
      alpha3: "CZE",
      ccTLD: ".CZ",
      iac: "+420",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Czech koruna (CZK, Kč)",
      "Language(s)": "Czech",
    },
    {
      entity: "Denmark",
      capital: "Copenhagen",
      num: 8,
      cc: "DK",
      alpha3: "DNK",
      ccTLD: ".DK",
      iac: "+45",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Danish krone (DKK, kr)",
      "Language(s)": "Danish, and Faroese, German, Kalaallisut in some areas.",
    },
    {
      entity: "Djibouti",
      capital: "Djibouti",
      num: 12,
      cc: "DJ",
      alpha3: "DJI",
      ccTLD: ".DJ",
      iac: "+253",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Djiboutian franc (DJF, Fr)",
      "Language(s)": "Arabic, French",
    },
    {
      entity: "Dominica",
      capital: "Roseau",
      num: 12,
      cc: "DM",
      alpha3: "DMA",
      ccTLD: ".DM",
      iac: "+1 767",
      idd: "011",
      timezone: "UTC-04:00",
      currency: "East Caribbean dollar (XCD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Dominican Republic",
      capital: "Santo Domingo",
      num: 11,
      cc: "DO",
      alpha3: "DOM",
      ccTLD: ".DO",
      iac: "+1 809 / 829 / 849",
      idd: "011",
      timezone: "UTC-04:00",
      currency: "Dominican peso (DOP, $)",
      "Language(s)": "Spanish",
    },
    {
      entity: "Ecuador",
      capital: "Quito",
      num: 12,
      cc: "EC",
      alpha3: "ECU",
      ccTLD: ".EC",
      iac: "+593",
      idd: "00",
      timezone: "UTC-05:00",
      currency: "United States dollar (USD, $)",
      "Language(s)":
        "Spanish (Quechua and Shuar, ancient languages are official in some territories.)",
    },
    {
      entity: "Egypt",
      capital: "Cairo",
      num: 12,
      cc: "EG",
      alpha3: "EGY",
      ccTLD: ".EG",
      iac: "+20",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Egyptian pound (EGP, £ or ج.? )",
      "Language(s)": "Arabic, Coptic (de jure language of the Coptic Church)",
    },
    {
      entity: "El Salvador",
      capital: "San Salvador",
      num: 8,
      cc: "SV",
      alpha3: "SLV",
      ccTLD: ".SV",
      iac: "+503",
      idd: "00",
      timezone: "UTC-06:00",
      currency: "Salvadoran colón (SVC, ₡), United States dollar (USD, $)",
      "Language(s)": "Spanish",
    },
    {
      entity: "Equatorial Guinea",
      capital: "Malabo",
      num: 12,
      cc: "GQ",
      alpha3: "GNQ",
      ccTLD: ".GQ",
      iac: "+240",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Central African CFA franc (XAF, Fr)",
      "Language(s)": "Spanish, French",
    },
    {
      entity: "Eritrea",
      capital: "Asmara",
      num: 12,
      cc: "ER",
      alpha3: "ERI",
      ccTLD: ".ER",
      iac: "+291",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Eritrean nakfa (ERN, Nfk)",
      "Language(s)": "Arabic, Tigrinya (working language)",
    },
    {
      entity: "Estonia",
      capital: "Tallinn",
      num: 10,
      cc: "EE",
      alpha3: "EST",
      ccTLD: ".EE",
      iac: "+372",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Estonian, Russian (de jure minority language)",
    },
    {
      entity: "Ethiopia",
      capital: "Addis Ababa",
      num: 10,
      cc: "ET",
      alpha3: "ETH",
      ccTLD: ".ET",
      iac: "+251",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Ethiopian birr (ETB, Br)",
      "Language(s)": "Amharic (working language)",
    },
    {
      entity: "Fiji",
      capital: "Suva",
      num: 12,
      cc: "FJ",
      alpha3: "FJI",
      ccTLD: ".FJ",
      iac: "+679",
      idd: "00",
      timezone: "UTC+12:00",
      currency: "Fijian dollar (FJD, $)",
      "Language(s)": "English, Fijian, Hindustani",
    },
    {
      entity: "Finland",
      capital: "Helsinki",
      num: 9,
      cc: "FI",
      alpha3: "FIN",
      ccTLD: ".FI",
      iac: "+358",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Finnish, Swedish, Sami",
    },
    {
      entity: "France",
      capital: "Paris",
      num: 9,
      cc: "FR",
      alpha3: "FRA",
      ccTLD: ".FR",
      iac: "+33",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)":
        "French (statewide), Corsican (in Corsica), Breton (in Brittany)",
    },
    {
      entity: "French Guiana",
      capital: "Cayenne",
      num: 12,
      cc: "GF",
      alpha3: "GUF",
      ccTLD: ".GF",
      iac: "+594",
      idd: "00",
      timezone: "UTC-01:00",
      currency: "",
      "Language(s)": "",
    },
    {
      entity: "French Polynesia",
      capital: "Papeete",
      num: 12,
      cc: "PF",
      alpha3: "PYF",
      ccTLD: ".PF",
      iac: "+689",
      idd: "00",
      timezone: "UTC-10:00",
      currency: "CFP franc (XPF, Fr)",
      "Language(s)": "French",
    },
    {
      entity: "Gabon",
      capital: "Libreville",
      num: 12,
      cc: "GA",
      alpha3: "GAB",
      ccTLD: ".GA",
      iac: "+241",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Central African CFA franc (XAF, Fr)",
      "Language(s)": "French",
    },
    {
      entity: "Gambia",
      capital: "Banjul",
      num: 12,
      cc: "GM",
      alpha3: "GMB",
      ccTLD: ".GM",
      iac: "+220",
      idd: "00",
      timezone: "UTC",
      currency: "Gambian dalasi (GMD, D)",
      "Language(s)": "English",
    },
    {
      entity: "Georgia",
      capital: "Tbilisi",
      num: 12,
      cc: "GE",
      alpha3: "GEO",
      ccTLD: ".GE",
      iac: "+995",
      idd: "8~10",
      timezone: "UTC+04:00",
      currency: "Georgian lari (GEL, ლ)",
      "Language(s)":
        "Georgian (statewide), Abkhaz (in Abkhazia), Ossetic (in South Ossetia), Russian (in Abkhazia and South Ossetia)",
    },
    {
      entity: "Germany",
      capital: "Berlin",
      num: 12,
      cc: "DE",
      alpha3: "DEU",
      ccTLD: ".DE",
      iac: "+49",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "German (de facto)",
    },
    {
      entity: "Ghana",
      capital: "Accra",
      num: 12,
      cc: "GH",
      alpha3: "GHA",
      ccTLD: ".GH",
      iac: "+233",
      idd: "00",
      timezone: "UTC",
      currency: "Ghanaian cedi (GHS, ₵)",
      "Language(s)": "English, and some other languages in some territories.",
    },
    {
      entity: "Greece",
      capital: "Athens",
      num: 13,
      cc: "GR",
      alpha3: "GRC",
      ccTLD: ".GR",
      iac: "+30",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Greek",
    },
    {
      entity: "Grenada",
      capital: "St. George's",
      num: 13,
      cc: "GD",
      alpha3: "GRD",
      ccTLD: ".GD",
      iac: "+1 473",
      idd: "011",
      timezone: "UTC-04:00",
      currency: "East Caribbean dollar (XCD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Guam",
      capital: "Hagåtña",
      num: 13,
      cc: "GU",
      alpha3: "GUM",
      ccTLD: ".GU",
      iac: "+1 671",
      idd: "011",
      timezone: "UTC+10:00",
      currency: "United States dollar (USD, $)",
      "Language(s)": "English and Chamorro",
    },
    {
      entity: "Guatemala",
      capital: "Guatemala City",
      num: 8,
      cc: "GT",
      alpha3: "GTM",
      ccTLD: ".GT",
      iac: "+502",
      idd: "00",
      timezone: "UTC-06:00",
      currency: "Guatemalan quetzal (GTQ, Q)",
      "Language(s)": "Spanish",
    },
    {
      entity: "Guinea",
      capital: "Conakry",
      num: 8,
      cc: "GN",
      alpha3: "GIN",
      ccTLD: ".GN",
      iac: "+224",
      idd: "00",
      timezone: "UTC",
      currency: "Guinean franc (GNF, Fr)",
      "Language(s)":
        "French, Fula (national), Maninka (national), Susu (national)",
    },
    {
      entity: "Guinea-Bissau",
      capital: "Bissau",
      num: 8,
      cc: "GW",
      alpha3: "GNB",
      ccTLD: ".GW",
      iac: "+245",
      idd: "00",
      timezone: "UTC",
      currency: "West African CFA franc (XOF, Fr)",
      "Language(s)": "Portuguese",
    },
    {
      entity: "Guyana",
      capital: "Georgetown",
      num: 12,
      cc: "GY",
      alpha3: "GUY",
      ccTLD: ".GY",
      iac: "+592",
      idd: "001",
      timezone: "UTC-03:00",
      currency: "Guyanese dollar (GYD, $)",
      "Language(s)": "English (official), Guyanese Creole (national)",
    },
    {
      entity: "Haiti",
      capital: "Port-au-Prince",
      num: 8,
      cc: "HT",
      alpha3: "HTI",
      ccTLD: ".HT",
      iac: "+509",
      idd: "00",
      timezone: "UTC-05:00",
      currency: "Haitian gourde (HTG, G)",
      "Language(s)": "French, Haitian Creole",
    },
    {
      entity: "Honduras",
      capital: "Tegucigalpa",
      num: 12,
      cc: "HN",
      alpha3: "HND",
      ccTLD: ".HN",
      iac: "+504",
      idd: "00",
      timezone: "UTC-06:00",
      currency: "Honduran lempira (HNL, L)",
      "Language(s)":
        "Spanish, and Garifuna, English, Miskito in some territories.",
    },
    {
      entity: "Hong Kong",
      capital: "",
      num: 8,
      cc: "HK",
      alpha3: "HKG",
      ccTLD: ".HK",
      iac: "+852",
      idd: "001",
      timezone: "UTC+08:00",
      currency: "Hong Kong dollar (HKD, $)",
      "Language(s)": "Cantonese, English",
    },
    {
      entity: "Hungary",
      capital: "Budapest",
      num: 8,
      cc: "HU",
      alpha3: "HUN",
      ccTLD: ".HU",
      iac: "+36",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Hungarian forint (HUF, Ft)",
      "Language(s)": "Hungarian",
    },
    {
      entity: "Iceland",
      capital: "Reykjavík",
      num: 7,
      cc: "IS",
      alpha3: "ISL",
      ccTLD: ".IS",
      iac: "+354",
      idd: "00",
      timezone: "UTC",
      currency: "Icelandic króna (ISK, kr)",
      "Language(s)": "Icelandic, Icelandic Sign Language",
    },
    {
      entity: "India",
      capital: "New Delhi",
      num: 10,
      cc: "IN",
      alpha3: "IND",
      ccTLD: ".IN",
      iac: "+91",
      idd: "00",
      timezone: "UTC+05:30",
      currency: "Indian rupee (INR, ₹)",
      "Language(s)":
        "English (statewide), Hindi, and some other languages in some territories.",
    },
    {
      entity: "Indonesia",
      capital: "Jakarta",
      num: 13,
      cc: "ID",
      alpha3: "IDN",
      ccTLD: ".ID",
      iac: "+62",
      idd: "001, 008",
      timezone: "UTC+07:00 - UTC+09:00",
      currency: "Indonesian rupiah (IDR, Rp)",
      "Language(s)":
        "Indonesian (national and official), and some other languages in some territories.",
    },
    {
      entity: "Iran",
      capital: "Tehran",
      num: 10,
      cc: "IR",
      alpha3: "IRN",
      ccTLD: ".IR",
      iac: "+98",
      idd: "00",
      timezone: "UTC+03:30",
      currency: "Iranian rial (IRR, ﷼)",
      "Language(s)":
        "Persian (statewide), and some other languages in some territories.",
    },
    {
      entity: "Iraq",
      capital: "Baghdad",
      num: 12,
      cc: "IQ",
      alpha3: "IRQ",
      ccTLD: ".IQ",
      iac: "+964",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Iraqi dinar (IQD, ع.د)",
      "Language(s)":
        "Arabic statewide, (Kurdish, Assyrian Neo-Aramaic, Iraqi Turkmen in some areas)",
    },
    {
      entity: "Ireland",
      capital: "Dublin",
      num: 9,
      cc: "IE",
      alpha3: "IRL",
      ccTLD: ".IE",
      iac: "+353",
      idd: "00",
      timezone: "UTC",
      currency: "Euro (EUR, €)",
      "Language(s)": "Irish (national), English (national)",
    },
    {
      entity: "Israel",
      capital: "Jerusalem",
      num: 10,
      cc: "IL",
      alpha3: "ISR",
      ccTLD: ".IL",
      iac: "+972",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Israeli new shekel (ILS, ₪)",
      "Language(s)": "Hebrew (de facto official), Arabic (co-official)",
    },
    {
      entity: "Italy",
      capital: "Rome",
      num: 10,
      cc: "IT",
      alpha3: "ITA",
      ccTLD: ".IT",
      iac: "+39",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Italian, and some other languages in some territories.",
    },
    {
      entity: "Jamaica",
      capital: "Kingston",
      num: 11,
      cc: "JM",
      alpha3: "JAM",
      ccTLD: ".JM",
      iac: "+1 876",
      idd: "011",
      timezone: "UTC-05:00",
      currency: "Jamaican dollar (JMD, $)",
      "Language(s)": "English, Jamaican patois (national language)",
    },
    {
      entity: "Japan",
      capital: "Tokyo",
      num: 10,
      cc: "JP",
      alpha3: "JPN",
      ccTLD: ".JP",
      iac: "+81",
      idd: "001",
      timezone: "UTC+09:00",
      currency: "Japanese yen (JPY, ¥)",
      "Language(s)": "Japanese (de facto)",
    },
    {
      entity: "Jordan",
      capital: "Amman",
      num: 12,
      cc: "JO",
      alpha3: "JOR",
      ccTLD: ".JO",
      iac: "+962",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Jordanian dinar (JOD, د.ا)",
      "Language(s)": "Arabic",
    },
    {
      entity: "Kazakhstan",
      capital: "Astana",
      num: 10,
      cc: "KZ",
      alpha3: "KAZ",
      ccTLD: ".KZ",
      iac: "+7 6xx, 7xx",
      idd: "8~10",
      timezone: "UTC+06:00",
      currency: "Kazakhstani tenge (KZT, ₸)",
      "Language(s)": "Kazakh (national), Russian",
    },
    {
      entity: "Kenya",
      capital: "Nairobi",
      num: 12,
      cc: "KE",
      alpha3: "KEN",
      ccTLD: ".KE",
      iac: "+254",
      idd: "000",
      timezone: "UTC+03:00",
      currency: "Kenyan shilling (KES, Sh)",
      "Language(s)": "English, Swahili (national)",
    },
    {
      entity: "Kiribati",
      capital: "Tarawa",
      num: 12,
      cc: "KI",
      alpha3: "KIR",
      ccTLD: ".KI",
      iac: "+686",
      idd: "00",
      timezone: "UTC+12:00",
      currency: "Australian dollar (AUD, $), Kiribati dollar (None, $)",
      "Language(s)": "English, Kiribati (national)",
    },
    {
      entity: "Kuwait",
      capital: "Kuwait City",
      num: 13,
      cc: "KW",
      alpha3: "KWT",
      ccTLD: ".KW",
      iac: "+965",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Kuwaiti dinar (KWD, د.ك)",
      "Language(s)": "Arabic",
    },
    {
      entity: "Kyrgyzstan",
      capital: "Bishkek",
      num: 9,
      cc: "KG",
      alpha3: "KGZ",
      ccTLD: ".KG",
      iac: "+996",
      idd: "00",
      timezone: "UTC+06:00",
      currency: "Kyrgyzstani som (KGS, лв)",
      "Language(s)": "Kirghiz (national), Russian",
    },
    {
      entity: "Laos",
      capital: "Vientiane",
      num: 12,
      cc: "LA",
      alpha3: "LAO",
      ccTLD: ".LA",
      iac: "+856",
      idd: "00",
      timezone: "UTC+07:00",
      currency: "Lao kip (LAK, ₭)",
      "Language(s)": "Lao",
    },
    {
      entity: "Latvia",
      capital: "Riga",
      num: 8,
      cc: "LV",
      alpha3: "LVA",
      ccTLD: ".LV",
      iac: "+371",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Latvian lats (LVL, Ls)",
      "Language(s)":
        "Latvian, Russian (minority language), Latgalian (regional language in Latgale)",
    },
    {
      entity: "Lebanon",
      capital: "Beirut",
      num: 13,
      cc: "LB",
      alpha3: "LBN",
      ccTLD: ".LB",
      iac: "+961",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Lebanese pound (LBP, ل.ل)",
      "Language(s)": "Arabic, French, Armenian (regional in Bourj Hammoud)",
    },
    {
      entity: "Lesotho",
      capital: "Maseru",
      num: 12,
      cc: "LS",
      alpha3: "LSO",
      ccTLD: ".LS",
      iac: "+266",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Lesotho loti (LSL, L), South African rand (ZAR, R)",
      "Language(s)": "English, Sotho (national)",
    },
    {
      entity: "Liberia",
      capital: "Monrovia",
      num: 12,
      cc: "LR",
      alpha3: "LBR",
      ccTLD: ".LR",
      iac: "+231",
      idd: "00",
      timezone: "UTC",
      currency: "Liberian dollar (LRD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Libya",
      capital: "Tripoli",
      num: 13,
      cc: "LY",
      alpha3: "LBY",
      ccTLD: ".LY",
      iac: "+218",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Libyan dinar (LYD, ل.د)",
      "Language(s)": "Arabic",
    },
    {
      entity: "Liechtenstein",
      capital: "Vaduz",
      num: 13,
      cc: "LI",
      alpha3: "LIE",
      ccTLD: ".LI",
      iac: "+423",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Swiss franc (CHF, Fr)",
      "Language(s)": "German",
    },
    {
      entity: "Lithuania",
      capital: "Vilnius",
      num: 13,
      cc: "LT",
      alpha3: "LTU",
      ccTLD: ".LT",
      iac: "+370",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Lithuanian litas (LTL, Lt)",
      "Language(s)": "Lithuanian",
    },
    {
      entity: "Luxembourg",
      capital: "Luxembourg",
      num: 13,
      cc: "LU",
      alpha3: "LUX",
      ccTLD: ".LU",
      iac: "+352",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "French, German, Luxembourgish (national)",
    },
    {
      entity: "Macau",
      capital: "",
      num: 13,
      cc: "MO",
      alpha3: "MAC",
      ccTLD: ".MO",
      iac: "+853",
      idd: "00",
      timezone: "UTC+08:00",
      currency: "Macanese pataca (MOP, P)",
      "Language(s)": "Cantonese, Portuguese",
    },
    {
      entity: "Macedonia",
      capital: "Skopje",
      num: 13,
      cc: "MK",
      alpha3: "MKD",
      ccTLD: ".MK",
      iac: "+389",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Macedonian denar (MKD, ден)",
      "Language(s)": "Macedonian (statewide)",
    },
    {
      entity: "Madagascar",
      capital: "Antananarivo",
      num: 13,
      cc: "MG",
      alpha3: "MDG",
      ccTLD: ".MG",
      iac: "+261",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Malagasy ariary (MGA, Ar)",
      "Language(s)": "French(official), Malagasy (national)",
    },
    {
      entity: "Malawi",
      capital: "Lilongwe",
      num: 454,
      cc: "MW",
      alpha3: "MWI",
      ccTLD: ".MW",
      iac: "+265",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Malawian kwacha (MWK, MK)",
      "Language(s)": "Chichewa (national), English(official)",
    },
    {
      entity: "Malaysia",
      capital: "Kuala Lumpur",
      num: 10,
      cc: "MY",
      alpha3: "MYS",
      ccTLD: ".MY",
      iac: "+60",
      idd: "00",
      timezone: "UTC+08:00",
      currency: "Malaysian ringgit (MYR, RM)",
      "Language(s)": "Malay (national), English (official for some purposes)",
    },
    {
      entity: "Maldives",
      capital: "Malé",
      num: 12,
      cc: "MV",
      alpha3: "MDV",
      ccTLD: ".MV",
      iac: "+960",
      idd: "00",
      timezone: "UTC+05:00",
      currency: "Maldivian rufiyaa (MVR, ރ.)",
      "Language(s)": "Dhivehi",
    },
    {
      entity: "Mali",
      capital: "Bamako",
      num: 12,
      cc: "ML",
      alpha3: "MLI",
      ccTLD: ".ML",
      iac: "+223",
      idd: "00",
      timezone: "UTC",
      currency: "West African CFA franc (XOF, Fr)",
      "Language(s)": "French",
    },
    {
      entity: "Malta",
      capital: "Valletta",
      num: 12,
      cc: "MT",
      alpha3: "MLT",
      ccTLD: ".MT",
      iac: "+356",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Maltese (national), English",
    },
    {
      entity: "Marshall Islands",
      capital: "Majuro",
      num: 12,
      cc: "MH",
      alpha3: "MHL",
      ccTLD: ".MH",
      iac: "+692",
      idd: "011",
      timezone: "UTC+10:00",
      currency: "United States dollar (USD, $)",
      "Language(s)": "English, Marshallese (national)",
    },
    {
      entity: "Martinique",
      capital: "",
      num: 12,
      cc: "MQ",
      alpha3: "MTQ",
      ccTLD: ".MQ",
      iac: "+596",
      idd: "00",
      timezone: "UTC-04:00",
      currency: "",
      "Language(s)": "",
    },
    {
      entity: "Mauritania",
      capital: "Nouakchott",
      num: 12,
      cc: "MR",
      alpha3: "MRT",
      ccTLD: ".MR",
      iac: "+222",
      idd: "00",
      timezone: "UTC",
      currency: "Mauritanian ouguiya (MRO, UM)",
      "Language(s)":
        "Arabic (national), French, Fula (national), Soninke (national), Wolof (national)",
    },
    {
      entity: "Mauritius",
      capital: "Port Louis",
      num: 12,
      cc: "MU",
      alpha3: "MUS",
      ccTLD: ".MU",
      iac: "+230",
      idd: "00",
      timezone: "UTC+04:00",
      currency: "Mauritian rupee (MUR, ₨)",
      "Language(s)": "English",
    },
    {
      entity: "Mexico",
      capital: "Mexico City",
      num: 10,
      cc: "MX",
      alpha3: "MEX",
      ccTLD: ".MX",
      iac: "+52",
      idd: "00",
      timezone: "UTC-08:00 - UTC-06:00",
      currency: "Mexican peso (MXN, $)",
      "Language(s)": "Spanish de facto",
    },
    {
      entity: "Micronesia, Federated States of",
      capital: "Palikir",
      num: 12,
      cc: "FM",
      alpha3: "FSM",
      ccTLD: ".FM",
      iac: "+691",
      idd: "011",
      timezone: "UTC+10:00",
      currency: "Micronesian dollar (None, $), United States dollar (USD, $)",
      "Language(s)":
        "English, Chuukese (in Chuuk), Kosraean (in Kosrae), Pohnpeian (in Pohnpei), Ulithian (in Yap), Yapese (in Yap)",
    },
    {
      entity: "Moldova, Republic of",
      capital: "Chisinau",
      num: 8,
      cc: "MD",
      alpha3: "MDA",
      ccTLD: ".MD",
      iac: "+373",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Moldovan leu (MDL, L)",
      "Language(s)":
        "Romanian, and Gagauz/Russian/Ukrainian are regional languages",
    },
    {
      entity: "Monaco",
      capital: "Monaco",
      num: 12,
      cc: "MC",
      alpha3: "MCO",
      ccTLD: ".MC",
      iac: "+377",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "French",
    },
    {
      entity: "Mongolia",
      capital: "Ulaanbaatar",
      num: 12,
      cc: "MN",
      alpha3: "MNG",
      ccTLD: ".MN",
      iac: "+976",
      idd: "001",
      timezone: "UTC+08:00",
      currency: "Mongolian tögrög (MNT, ₮)",
      "Language(s)": "Mongolian",
    },
    {
      entity: "Montenegro",
      capital: "Podgorica",
      num: 12,
      cc: "ME",
      alpha3: "MNE",
      ccTLD: ".ME",
      iac: "+382",
      idd: "",
      timezone: "UTC+01",
      currency: "Euro (EUR, €)",
      "Language(s)":
        "Montenegrin (national), Albanian/Bosnian/Croatian/Serbian are regional languages.",
    },
    {
      entity: "Morocco",
      capital: "Rabat",
      num: 12,
      cc: "MA",
      alpha3: "MAR",
      ccTLD: ".MA",
      iac: "+212",
      idd: "00",
      timezone: "UTC",
      currency: "Moroccan dirham (MAD, د.? .)",
      "Language(s)": "Amazigh, Arabic",
    },
    {
      entity: "Mozambique",
      capital: "Maputo",
      num: 12,
      cc: "MZ",
      alpha3: "MOZ",
      ccTLD: ".MZ",
      iac: "+258",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Mozambican metical (MZN, MTn)",
      "Language(s)": "Portuguese",
    },
    {
      entity: "Myanmar (Burma)",
      capital: "Naypyidaw",
      num: 13,
      cc: "MM",
      alpha3: "MMR",
      ccTLD: ".MM",
      iac: "+95",
      idd: "00",
      timezone: "UTC+06:30",
      currency: "Myanma kyat (MMK, K)",
      "Language(s)": "Burmese",
    },
    {
      entity: "Namibia",
      capital: "Windhoek",
      num: 13,
      cc: "NA",
      alpha3: "NAM",
      ccTLD: ".NA",
      iac: "+264",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Namibian dollar (NAD, $), South African rand (ZAR, R)",
      "Language(s)":
        "English, Afrikaans (national), German(regional), Oshiwambo (regional)",
    },
    {
      entity: "Nauru",
      capital: "Yaren",
      num: 13,
      cc: "NR",
      alpha3: "NRU",
      ccTLD: ".NR",
      iac: "+674",
      idd: "00",
      timezone: "UTC+12:00",
      currency: "Australian dollar (AUD, $), Nauruan dollar (None, $)",
      "Language(s)": "English, Nauruan",
    },
    {
      entity: "Nepal",
      capital: "Kathmandu",
      num: 13,
      cc: "NP",
      alpha3: "NPL",
      ccTLD: ".NP",
      iac: "+977",
      idd: "00",
      timezone: "UTC+05:30",
      currency: "Nepalese rupee (NPR, ₨)",
      "Language(s)": "Nepali",
    },
    {
      entity: "Netherlands",
      capital: "Amsterdam",
      num: 10,
      cc: "NL",
      alpha3: "NLD",
      ccTLD: ".NL",
      iac: "+31",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)":
        "Dutch (statewide), and some other languages in some territories.",
    },
    {
      entity: "New Caledonia",
      capital: "Nouméa",
      num: 12,
      cc: "NC",
      alpha3: "NCL",
      ccTLD: ".NC",
      iac: "+687",
      idd: "00",
      timezone: "UTC+11:00",
      currency: "CFP franc (XPF, Fr)",
      "Language(s)": "French",
    },
    {
      entity: "New Zealand",
      capital: "Wellington",
      num: 10,
      cc: "NZ",
      alpha3: "NZL",
      ccTLD: ".NZ",
      iac: "+64",
      idd: "00",
      timezone: "UTC+12:00",
      currency: "New Zealand dollar (NZD, $)",
      "Language(s)": "English(de facto)",
    },
    {
      entity: "Nicaragua",
      capital: "Managua",
      num: 10,
      cc: "NI",
      alpha3: "NIC",
      ccTLD: ".NI",
      iac: "+505",
      idd: "00",
      timezone: "UTC-06:00",
      currency: "Nicaraguan córdoba (NIO, C$)",
      "Language(s)": "Spanish",
    },
    {
      entity: "Niger",
      capital: "Niamey",
      num: 12,
      cc: "NE",
      alpha3: "NER",
      ccTLD: ".NE",
      iac: "+227",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "West African CFA franc (XOF, Fr)",
      "Language(s)":
        "French, (Hausa/Fulfulde/Gulmancema etc. are national languages)",
    },
    {
      entity: "Nigeria",
      capital: "Abuja",
      num: 12,
      cc: "NG",
      alpha3: "NGA",
      ccTLD: ".NG",
      iac: "+234",
      idd: "009",
      timezone: "UTC+01:00",
      currency: "Nigerian naira (NGN, ₦)",
      "Language(s)": "English",
    },
    {
      entity: "North Korea",
      capital: "Pyongyang",
      num: 12,
      cc: "KP",
      alpha3: "PRK",
      ccTLD: ".KP",
      iac: "+850",
      idd: "00",
      timezone: "UTC+09:00",
      currency: "North Korean won (KPW, ₩)",
      "Language(s)": "Korean",
    },
    {
      entity: "Norway",
      capital: "Oslo",
      num: 8,
      cc: "NO",
      alpha3: "NOR",
      ccTLD: ".NO",
      iac: "+47",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Norwegian krone (NOK, kr)",
      "Language(s)": "Norwegian, Sami, Kven, Romani, Scandoromani",
    },
    {
      entity: "Oman",
      capital: "Muscat",
      num: 12,
      cc: "OM",
      alpha3: "OMN",
      ccTLD: ".OM",
      iac: "+968",
      idd: "00",
      timezone: "UTC+04:00",
      currency: "Omani rial (OMR, ر.ع.)",
      "Language(s)": "Arabic",
    },
    {
      entity: "Pakistan",
      capital: "Islamabad",
      num: 10,
      cc: "PK",
      alpha3: "PAK",
      ccTLD: ".PK",
      iac: "+92",
      idd: "00",
      timezone: "UTC+05:00",
      currency: "Pakistani rupee (PKR, ₨)",
      "Language(s)":
        "Urdu (national), English (official), Sindhi (co-official in Sindh province)",
    },
    {
      entity: "Palau",
      capital: "Ngerulmud",
      num: 12,
      cc: "PW",
      alpha3: "PLW",
      ccTLD: ".PW",
      iac: "+680",
      idd: "011",
      timezone: "UTC+09:00",
      currency: "Palauan dollar (None, $), United States dollar (USD, $)",
      "Language(s)":
        "English, Palauan, Sonsorolese (in Sonsorol), Tobian (in Hatohobei), Japanese (in Angaur)",
    },
    {
      entity: "Panama",
      capital: "Panama City",
      num: 12,
      cc: "PA",
      alpha3: "PAN",
      ccTLD: ".PA",
      iac: "+507",
      idd: "00",
      timezone: "UTC-05:00",
      currency: "Panamanian balboa (PAB, B/.), United States dollar (USD, $)",
      "Language(s)": "Spanish",
    },
    {
      entity: "Papua New Guinea",
      capital: "Port Moresby",
      num: 12,
      cc: "PG",
      alpha3: "PNG",
      ccTLD: ".PG",
      iac: "+675",
      idd: "05",
      timezone: "UTC+10:00",
      currency: "Papua New Guinean kina (PGK, K)",
      "Language(s)": "English, Hiri Motu, Tok Pisin",
    },
    {
      entity: "Paraguay",
      capital: "Asunción",
      num: 13,
      cc: "PY",
      alpha3: "PRY",
      ccTLD: ".PY",
      iac: "+595",
      idd: "002",
      timezone: "UTC-04:00",
      currency: "Paraguayan guaraní (PYG, ₲)",
      "Language(s)": "Spanish, Guaraní",
    },
    {
      entity: "Peru",
      capital: "Lima",
      num: 13,
      cc: "PE",
      alpha3: "PER",
      ccTLD: ".PE",
      iac: "+51",
      idd: "00",
      timezone: "UTC-05:00",
      currency: "Peruvian nuevo sol (PEN, S/.)",
      "Language(s)":
        "Spanish, Aymara, Quechua, All native languages in areas where they are spoken by the majority of people",
    },
    {
      entity: "Philippines",
      capital: "Manila",
      num: 11,
      cc: "PH",
      alpha3: "PHL",
      ccTLD: ".PH",
      iac: "+63",
      idd: "00",
      timezone: "UTC+08:00",
      currency: "Philippine peso (PHP, ₱)",
      "Language(s)":
        "English, Filipino(national), and some other languages in some territories.",
    },
    {
      entity: "Poland",
      capital: "Warsaw",
      num: 9,
      cc: "PL",
      alpha3: "POL",
      ccTLD: ".PL",
      iac: "+48",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Polish złoty (PLN, zł)",
      "Language(s)": "Polish (sole official language of state)",
    },
    {
      entity: "Portugal",
      capital: "Lisbon",
      num: 12,
      cc: "PT",
      alpha3: "PRT",
      ccTLD: ".PT",
      iac: "+351",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Portuguese (official), Mirandese (regional)",
    },
    {
      entity: "Puerto Rico",
      capital: "San Juan",
      num: 10,
      cc: "PR",
      alpha3: "PRI",
      ccTLD: ".PR",
      iac: "+1 787 / 939",
      idd: "011",
      timezone: "UTC-04:00",
      currency: "United States dollar (USD, $)",
      "Language(s)": "Spanish and English",
    },
    {
      entity: "Qatar",
      capital: "Doha",
      num: 12,
      cc: "QA",
      alpha3: "QAT",
      ccTLD: ".QA",
      iac: "+974",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Qatari riyal (QAR, ر.ق)",
      "Language(s)": "Arabic",
    },
    {
      entity: "Réunion",
      capital: "",
      num: 12,
      cc: "RE",
      alpha3: "REU",
      ccTLD: ".RE",
      iac: "+262",
      idd: "00",
      timezone: "UTC+04:00",
      currency: "",
      "Language(s)": "",
    },
    {
      entity: "Romania",
      capital: "Bucharest",
      num: 13,
      cc: "RO",
      alpha3: "ROU",
      ccTLD: ".RO",
      iac: "+40",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Romanian leu (RON, L)",
      "Language(s)": "Romanian (statewide), and other minority languages.",
    },
    {
      entity: "Russia",
      capital: "Moscow",
      num: 7,
      cc: "RU",
      alpha3: "RUS",
      ccTLD: ".RU",
      iac: "+7",
      idd: "8~10",
      timezone: "UTC+03:00",
      currency: "Russian ruble (RUB, р.)",
      "Language(s)":
        "Russian (federal; official), and some other languages in some territories.",
    },
    {
      entity: "Rwanda",
      capital: "Kigali",
      num: 12,
      cc: "RW",
      alpha3: "RWA",
      ccTLD: ".RW",
      iac: "+250",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Rwandan franc (RWF, Fr)",
      "Language(s)": "English, French, Kinyarwanda",
    },
    {
      entity: "Saint Kitts and Nevis",
      capital: "Basseterre",
      num: 12,
      cc: "KN",
      alpha3: "KNA",
      ccTLD: ".KN",
      iac: "+1 869",
      idd: "011",
      timezone: "UTC-04:00",
      currency: "East Caribbean dollar (XCD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Saint Lucia",
      capital: "Castries",
      num: 12,
      cc: "LC",
      alpha3: "LCA",
      ccTLD: ".LC",
      iac: "+1 758",
      idd: "011",
      timezone: "UTC-04:00",
      currency: "East Caribbean dollar (XCD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Saint Vincent and the Grenadines",
      capital: "Kingstown",
      num: 12,
      cc: "VC",
      alpha3: "VCT",
      ccTLD: ".VC",
      iac: "+1 784",
      idd: "011",
      timezone: "UTC-04",
      currency: "East Caribbean dollar (XCD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Samoa",
      capital: "Apia",
      num: 12,
      cc: "WS",
      alpha3: "WSM",
      ccTLD: ".WS",
      iac: "+685",
      idd: "00",
      timezone: "UTC-11:00",
      currency: "Samoan tala (WST, T)",
      "Language(s)": "English (official), Samoan (national)",
    },
    {
      entity: "San Marino",
      capital: "San Marino",
      num: 12,
      cc: "SM",
      alpha3: "SMR",
      ccTLD: ".SM",
      iac: "+378",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Italian",
    },
    {
      entity: "São Tomé and Príncipe",
      capital: "São Tomé",
      num: 12,
      cc: "ST",
      alpha3: "STP",
      ccTLD: ".ST",
      iac: "+239",
      idd: "00",
      timezone: "UTC",
      currency: "São Tomé and Príncipe dobra (STD, Db)",
      "Language(s)": "Portuguese",
    },
    {
      entity: "Saudi Arabia",
      capital: "Riyadh",
      num: 12,
      cc: "SA",
      alpha3: "SAU",
      ccTLD: ".SA",
      iac: "+966",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Saudi riyal (SAR, ر.س)",
      "Language(s)": "Arabic",
    },
    {
      entity: "Senegal",
      capital: "Dakar",
      num: 12,
      cc: "SN",
      alpha3: "SEN",
      ccTLD: ".SN",
      iac: "+221",
      idd: "00",
      timezone: "UTC",
      currency: "West African CFA franc (XOF, Fr)",
      "Language(s)":
        "French, Jola-Fogny (national), Mandinka (national), Pulaar (national), Serer-Sine (national), Wolof (national)",
    },
    {
      entity: "Serbia",
      capital: "Belgrade",
      num: 12,
      cc: "RS",
      alpha3: "SRB",
      ccTLD: ".RS",
      iac: "+381",
      idd: "99",
      timezone: "UTC+01:00",
      currency: "Serbian dinar (RSD, дин. or din.)",
      "Language(s)":
        "Serbian (statewide), and some other languages in some territories.",
    },
    {
      entity: "Seychelles",
      capital: "Victoria",
      num: 12,
      cc: "SC",
      alpha3: "SYC",
      ccTLD: ".SC",
      iac: "+248",
      idd: "00",
      timezone: "UTC+04:00",
      currency: "Seychellois rupee (SCR, ₨)",
      "Language(s)": "English, French, Seychellois Creole",
    },
    {
      entity: "Sierra Leone",
      capital: "Freetown",
      num: 12,
      cc: "SL",
      alpha3: "SLE",
      ccTLD: ".SL",
      iac: "+232",
      idd: "00",
      timezone: "UTC",
      currency: "Sierra Leonean leone (SLL, Le)",
      "Language(s)": "English",
    },
    {
      entity: "Singapore",
      capital: "Singapore",
      num: 8,
      cc: "SG",
      alpha3: "SGP",
      ccTLD: ".SG",
      iac: "+65",
      idd: "001",
      timezone: "UTC+08:00",
      currency: "Brunei dollar (BND, $), Singapore dollar (SGD, $)",
      "Language(s)": "English, Malay (national), Chinese, Tamil",
    },
    {
      entity: "Slovakia",
      capital: "Bratislava",
      num: 12,
      cc: "SK",
      alpha3: "SVK",
      ccTLD: ".SK",
      iac: "+421",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)": "Slovak",
    },
    {
      entity: "Slovenia",
      capital: "Ljubljana",
      num: 12,
      cc: "SI",
      alpha3: "SVN",
      ccTLD: ".SI",
      iac: "+386",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)":
        "Slovene (statewide), Hungarian/Italian/Serbo-Croatian in some territories.",
    },
    {
      entity: "Solomon Islands",
      capital: "Honiara",
      num: 12,
      cc: "SB",
      alpha3: "SLB",
      ccTLD: ".SB",
      iac: "+677",
      idd: "00",
      timezone: "UTC+11:00",
      currency: "Solomon Islands dollar (SBD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Somalia",
      capital: "Mogadishu",
      num: 12,
      cc: "SO",
      alpha3: "SOM",
      ccTLD: ".SO",
      iac: "+252",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Somali shilling (SOS, Sh)",
      "Language(s)": "Somali (national)., Arabic",
    },
    {
      entity: "South Africa",
      capital: "Pretoria",
      num: 13,
      cc: "ZA",
      alpha3: "ZAF",
      ccTLD: ".ZA",
      iac: "+27",
      idd: "09",
      timezone: "UTC+02:00",
      currency: "South African rand (ZAR, R)",
      "Language(s)":
        "Afrikaans, English, Southern Ndebele, Northern Sotho, Sotho, Swazi, Tsonga, Tswana, Venda, Xhosa, Zulu",
    },
    {
      entity: "South Korea",
      capital: "Seoul",
      num: 12,
      cc: "KR",
      alpha3: "KOR",
      ccTLD: ".KR",
      iac: "+82",
      idd: "001",
      timezone: "UTC+09:00",
      currency: "South Korean won (KRW, ₩)",
      "Language(s)": "Korean",
    },
    {
      entity: "Spain",
      capital: "Madrid",
      num: 9,
      cc: "ES",
      alpha3: "ESP",
      ccTLD: ".ES",
      iac: "+34",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Euro (EUR, €)",
      "Language(s)":
        "Spanish (statewide), and some other languages in some territories.",
    },
    {
      entity: "Sri Lanka",
      capital: "Sri Jayawardenapura Kotte",
      num: 13,
      cc: "LK",
      alpha3: "LKA",
      ccTLD: ".LK",
      iac: "+94",
      idd: "00",
      timezone: "UTC+05:30",
      currency: "Sri Lankan rupee (LKR, Rs)",
      "Language(s)": "Sinhala (national), Tamil",
    },
    {
      entity: "Sudan",
      capital: "Khartoum",
      num: 13,
      cc: "SD",
      alpha3: "SDN",
      ccTLD: ".SD",
      iac: "+249",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Sudanese pound (SDG, £)",
      "Language(s)": "Arabic, English",
    },
    {
      entity: "Suriname",
      capital: "Paramaribo",
      num: 13,
      cc: "SR",
      alpha3: "SUR",
      ccTLD: ".SR",
      iac: "+597",
      idd: "00",
      timezone: "UTC-03:30",
      currency: "Surinamese dollar (SRD, $)",
      "Language(s)": "Dutch",
    },
    {
      entity: "Swaziland",
      capital: "Mbabane",
      num: 13,
      cc: "SZ",
      alpha3: "SWZ",
      ccTLD: ".SZ",
      iac: "+268",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Swazi lilangeni (SZL, L)",
      "Language(s)": "English, Swazi",
    },
    {
      entity: "Sweden",
      capital: "Stockholm",
      num: 9,
      cc: "SE",
      alpha3: "SWE",
      ccTLD: ".SE",
      iac: "+46",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Swedish krona (SEK, kr)",
      "Language(s)":
        "Swedish, and some other languages like Finnish, Meänkieli, Romani in some territories.",
    },
    {
      entity: "Switzerland",
      capital: "Bern",
      num: 9,
      cc: "CH",
      alpha3: "CHE",
      ccTLD: ".CH",
      iac: "+41",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Swiss franc (CHF, Fr)",
      "Language(s)": "German, French, Italian, Romansh",
    },
    {
      entity: "Syrian Arab Republic",
      capital: "Damascus",
      num: 12,
      cc: "SY",
      alpha3: "SYR",
      ccTLD: ".SY",
      iac: "+963",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Syrian pound (SYP, £ or ل.س)",
      "Language(s)": "Arabic",
    },
    {
      entity: "Taiwan",
      capital: "Taipei",
      num: 12,
      cc: "TW",
      alpha3: "TWN",
      ccTLD: ".TW",
      iac: "+886",
      idd: "002",
      timezone: "UTC+08:00",
      currency: "New Taiwan dollar (TWD, $)",
      "Language(s)": "Mandarin Chinese, Taiwanese (regional)",
    },
    {
      entity: "Tajikistan",
      capital: "Dushanbe",
      num: 12,
      cc: "TJ",
      alpha3: "TJK",
      ccTLD: ".TJ",
      iac: "+992",
      idd: "8~10",
      timezone: "UTC+06:00",
      currency: "Tajikistani somoni (TJS, ? М)",
      "Language(s)": "Tajik (national), Russian (for interethnic communication)",
    },
    {
      entity: "Tanzania",
      capital: "Dodoma",
      num: 12,
      cc: "TZ",
      alpha3: "TZA",
      ccTLD: ".TZ",
      iac: "+255",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Tanzanian shilling (TZS, Sh)",
      "Language(s)": "Swahili (national), English",
    },
    {
      entity: "Thailand",
      capital: "Bangkok",
      num: 13,
      cc: "TH",
      alpha3: "THA",
      ccTLD: ".TH",
      iac: "+66",
      idd: "001",
      timezone: "UTC+07:00",
      currency: "Thai baht (THB, ฿)",
      "Language(s)": "Thai",
    },
    {
      entity: "Togo",
      capital: "Lomé",
      num: 13,
      cc: "TG",
      alpha3: "TGO",
      ccTLD: ".TG",
      iac: "+228",
      idd: "00",
      timezone: "UTC",
      currency: "West African CFA franc (XOF, Fr)",
      "Language(s)": "French",
    },
    {
      entity: "Trinidad and Tobago",
      capital: "Port of Spain",
      num: 13,
      cc: "TT",
      alpha3: "TTO",
      ccTLD: ".TT",
      iac: "+1 868",
      idd: "011",
      timezone: "UTC-04:00",
      currency: "Trinidad and Tobago dollar (TTD, $)",
      "Language(s)": "English",
    },
    {
      entity: "Tunisia",
      capital: "Tunis",
      num: 13,
      cc: "TN",
      alpha3: "TUN",
      ccTLD: ".TN",
      iac: "+216",
      idd: "00",
      timezone: "UTC+01:00",
      currency: "Tunisian dinar (TND, د.ت)",
      "Language(s)": "Arabic (national), French",
    },
    {
      entity: "Turkey",
      capital: "Ankara",
      num: 10,
      cc: "TR",
      alpha3: "TUR",
      ccTLD: ".TR",
      iac: "+90",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Turkish lira (TRY, TL)",
      "Language(s)": "Turkish",
    },
    {
      entity: "Turkmenistan",
      capital: "Ashgabat",
      num: 12,
      cc: "TM",
      alpha3: "TKM",
      ccTLD: ".TM",
      iac: "+993",
      idd: "8~10",
      timezone: "UTC+05:00",
      currency: "Turkmenistani manat (TMT, m)",
      "Language(s)":
        "Turkmen (national), Russian (for interethnic communication)",
    },
    {
      entity: "Tuvalu",
      capital: "Funafuti",
      num: 12,
      cc: "TV",
      alpha3: "TUV",
      ccTLD: ".TV",
      iac: "+688",
      idd: "00",
      timezone: "UTC+12:00",
      currency: "Australian dollar (AUD, $), Tuvaluan dollar (None, $)",
      "Language(s)": "English, Tuvaluan (national)",
    },
    {
      entity: "Uganda",
      capital: "Kampala",
      num: 12,
      cc: "UG",
      alpha3: "UGA",
      ccTLD: ".UG",
      iac: "+256",
      idd: "000",
      timezone: "UTC+03:00",
      currency: "Ugandan shilling (UGX, Sh)",
      "Language(s)": "English, Swahili",
    },
    {
      entity: "Ukraine",
      capital: "Kiev",
      num: 9,
      cc: "UA",
      alpha3: "UKR",
      ccTLD: ".UA",
      iac: "+380",
      idd: "8~10",
      timezone: "UTC+03:00",
      currency: "Ukrainian hryvnia (UAH, ₴)",
      "Language(s)": "Ukrainian, Russian (regional), Crimean Tatar (regional)",
    },
    {
      entity: "United Arab Emirates",
      capital: "Abu Dhabi",
      num: 13,
      cc: "AE",
      alpha3: "ARE",
      ccTLD: ".AE",
      iac: "+971",
      idd: "00",
      timezone: "UTC+04:00",
      currency: "United Arab Emirates dirham (AED, د.إ)",
      "Language(s)": "Arabic",
    },
    {
      entity: "United Kingdom",
      capital: "London",
      num: 10,
      cc: "GB",
      alpha3: "GBR",
      ccTLD: ".GB\n.UK",
      iac: "+44",
      idd: "00",
      timezone: "UTC",
      currency: "British pound (GBP, £)",
      "Language(s)": "English, and some other languages in some territories.",
    },
    {
      entity: "United States",
      capital: "Washington, D.C.",
      num: 10,
      cc: "US",
      alpha3: "USA",
      ccTLD: ".US",
      iac: "+1",
      idd: "011",
      timezone: "UTC-11:00 - UTC-05:00",
      currency: "United States dollar (USD, $)",
      "Language(s)": "English (de facto)",
    },
    {
      entity: "Uruguay",
      capital: "Montevideo",
      num: 12,
      cc: "UY",
      alpha3: "URY",
      ccTLD: ".UY",
      iac: "+598",
      idd: "00",
      timezone: "UTC-03:00",
      currency: "Uruguayan peso (UYU, $)",
      "Language(s)": "Spanish",
    },
    {
      entity: "Uzbekistan",
      capital: "Tashkent",
      num: 9,
      cc: "UZ",
      alpha3: "UZB",
      ccTLD: ".UZ",
      iac: "+998",
      idd: "8~10",
      timezone: "UTC+06:00",
      currency: "Uzbekistani som (UZS, лв)",
      "Language(s)": "Uzbek (national), Russian (for interethnic communication)",
    },
    {
      entity: "Vanuatu",
      capital: "Port Vila",
      num: 12,
      cc: "VU",
      alpha3: "VUT",
      ccTLD: ".VU",
      iac: "+678",
      idd: "00",
      timezone: "UTC+11:00",
      currency: "Vanuatu vatu (VUV, Vt)",
      "Language(s)": "Bislama (national), English, French",
    },
    {
      entity: "Vatican City",
      capital: "Vatican City",
      num: 10,
      cc: "VA",
      alpha3: "VAT",
      ccTLD: ".VA",
      iac: "+39 06 698",
      idd: "00",
      timezone: "UTC+01",
      currency: "Euro (EUR, €)",
      "Language(s)": "Italian (de facto).",
    },
    {
      entity: "Venezuela",
      capital: "Caracas",
      num: 10,
      cc: "VE",
      alpha3: "VEN",
      ccTLD: ".VE",
      iac: "+58",
      idd: "00",
      timezone: "UTC-04:00",
      currency: "Venezuelan bolívar (VEF, Bs F)",
      "Language(s)": "Spanish",
    },
    {
      entity: "Vietnam",
      capital: "Hanoi",
      num: 13,
      cc: "VN",
      alpha3: "VNM",
      ccTLD: ".VN",
      iac: "+84",
      idd: "00",
      timezone: "UTC+07:00",
      currency: "Vietnamese đồng (VND, ₫)",
      "Language(s)": "Vietnamese",
    },
  
    {
      entity: "Yemen",
      capital: "Sanaá",
      num: 13,
      cc: "YE",
      alpha3: "YEM",
      ccTLD: ".YE",
      iac: "+967",
      idd: "00",
      timezone: "UTC+03:00",
      currency: "Yemeni rial (YER, ﷼)",
      "Language(s)": "Arabic",
    },
    {
      entity: "Zambia",
      capital: "Lusaka",
      num: 13,
      cc: "ZM",
      alpha3: "ZMB",
      ccTLD: ".ZM",
      iac: "+260",
      idd: "00",
      timezone: "UTC+02:00",
      currency: "Zambian kwacha (ZMK, ZK)",
      "Language(s)": "English",
    },
    {
      entity: "Zimbabwe",
      capital: "Harare",
      num: 13,
      cc: "ZW",
      alpha3: "ZWE",
      ccTLD: ".ZW",
      iac: "+263",
      idd: "00",
      timezone: "UTC+02:00",
      currency:
        "Botswana pula (BWP, P), British pound (GBP, £), Euro (EUR, €), South African rand (ZAR, R), United States dollar (USD, $), Zimbabwean dollar (ZWL, $)",
      "Language(s)": "English, Shona, Northern Ndebele",
    },
  ];
  
  export default countries;